name: Build
on:
  # schedule:
  #   - cron: "0 5 * * 1-5"
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Run node
        run: npm run start

      - name: Push codes
        run: |
          git config --global user.name 'rosiewingit' 
          git config --global user.email 'rosiewingit@gmail.com'
          git add -A
          git commit -m 'Automated commit by github action'
          git push
        env:
          GH_TOKEN: ${{ secrets.AUTOCI }}
